### ISSUE TITLE
is google-oauth2.0 currently working?

### ISSUE THREAD

**Issue by snuglinux** [rvk01/google-oauth2#30]
I want to use IMAP and SMTP

I get an error:
```
Error 401: deleted_client
The OAuth client was deleted
```

**Comment by rvk01** [comment]
Did you use your own client_id and client_secret (on line 191 and 192 of frmmain.pas)??
The one in the source code isn't valid anymore.
You need to register your own client_id (as is described on the main page in the readme.md).

**Comment by snuglinux** [comment]
Of course I added my client_id and client_secret, but that was not the cause of the error, I had to update IE and add Test users. 
Now I see the following log:

```
Authorizing...
Getting new Refresh_token
Using backup Authentication token (html), maybe the browser-title was cut off.
Getting new Refresh_token
We don't have access
```

**Comment by rvk01** [comment]
This version still uses the browser-title to retrieve the code. I'm working on a version where there is a local redirect (with synapse server code) to make the retrieving of the authentication code more reliable. I'll try to update this code soon.

**Comment by snuglinux** [comment]
Thanks, I'll be waiting! 
Is it possible to manually use the authorization code somehow?

**Comment by rvk01** [comment]
> Is it possible to manually use the authorization code somehow?
Yes, in the demo app there is a checkbox "Force manually input of authentication_token" (top-right). If you check that, you'll get an inputbox where you can enter the authorization code manually after you see that authorization code in the browser (or browser-title). If you have your own app you can set gOAuth2.ForceManualAuth := true;
In that case, the code to detect the authorization_token from the browser-title is disabled.

**Comment by snuglinux** [comment]
Thanks for the quick response! I tried manually entering authentication_token as you wrote, but the result is the same. I will wait for a solution! I need to write a small program to send via smtp and view via imap using Gmail

**Comment by rvk01** [comment]
> Thanks for the quick response! I tried manually entering authentication_token as you wrote, but the result is the same. I will wait for a solution! I need to write a small program to send via smtp and view via imap using Gmail

I just pushed a new version where the authorization token is taken via a small server instance. (client_id is still not valid in this source) But you say you get the same result if you enter the authorization code manually. That should have worked. What error do you get? If it's still the "deleted_client" you'll need to create new client_id. For using SMTP you need a client_id with scope https://mail.google.com/. Otherwise you get an extra warning during authentication.

BTW. For access to SMTP you can still use app passwords. Even when switching to 2FA. So, if you have access to the app passwords of an account, you can just use username/app.password in your program without the whole authentication hassel. If you distribute your program and you NEED your users to allow access (so they don't have to create an app password) you could use this unit.

**Comment by snuglinux** [comment]
![image](https://user-images.githubusercontent.com/23461484/211913292-3d694fb9-0ba3-4a26-abca-22d883b06162.png)
I checked this after the update. Perhaps I'm setting something up wrong? Thanks for the hint to use username/app.password, I'll try it now!

**Comment by snuglinux** [comment]
Sending using app password fails: SMTP ERROR: MailFrom:530 5.7.0  https://support.google.com/mail/?p=WantAuthError l4-20020a05600012c400b002bbb2d43f65sm11759857wrx.14 - gsmtp
```
function smtp_connection(host, port, user, password: string): boolean;
begin
  Result := False;
  SMTP   := TSMTPSend.Create;
  try
    SMTP.TargetHost := host;
    SMTP.TargetPort := port;
    SMTP.Username   := user;
    SMTP.Password   := password;
    SMTP.FullSSL    := True;
    SMTP.AutoTLS    := True;
    if not SMTP.Login() then
    begin
      F3.M_log.Append('SMTP Login: ERROR');
      Result := False;
    end
    else
    begin
      Result := True;
    end;
  finally
  end;
end;

procedure SendMail(host, port, user, password, mail_from, mail_to, subject, mail_data: string);
var
  Email: TStringList;
begin
  Email := TStringList.Create;
  try
    Email.Add('From: "Me" <' + mail_from + '>');
    Email.Add('To: "You" <'  + mail_to   + '>');
    Email.Add('Subject: ' + subject + '');
    Email.Add('');
    Email.Add(mail_data);
    SMTP := TSMTPSend.Create;
    if not ( smtp_connection(host, port, user, password)) then
      Exit;
    try
       if not (SMTP.MailFrom(mail_from, Length(Email.Text))) then
       begin
          F3.M_log.Append('SMTP ERROR: MailFrom:' + SMTP.ResultString);
          Exit;
       end;
...
```

**Comment by rvk01** [comment]
> Sending using app password fails: SMTP ERROR: MailFrom:530 5.7.0 https://support.google.com/mail/?p=WantAuthError l4-20020a05600012c400b002bbb2d43f65sm11759857wrx.14 - gsmtp

Is 2-Step Verification enabled on that account? Because app passwords should only work with 2FA enabled. (I though Google and GMail switched to that as default but I could be wrong and that there is still 1FA available (in which case app passwords won't work)).

**Comment by rvk01** [comment]
>  I checked this after the update. Perhaps I'm setting something up wrong?

Did you set the client_id and client_secret in the client.dat file?
The default client_id in the source is invalid at the moment. You need your own client_id for now.

**Comment by snuglinux** [comment]
> Is 2-Step Verification enabled on that account? Because app passwords should only work with 2FA enabled. (I though Google and GMail switched to that as default but I could be wrong and that there is still 1FA available (in which case app passwords won't work)).

Thanks, I figured it out and it worked :)

**Comment by rvk01** [comment]
> > Is 2-Step Verification enabled on that account? Because app passwords should only work with 2FA enabled. (I though Google and GMail switched to that as default but I could be wrong and that there is still 1FA available (in which case app passwords won't work)).
> 
> Thanks, I figured it out and it worked :)

Glad to hear it. When you have control over the account, setting an app password is much easier than using OAuth2. Only when distributing a program and wanting the users not to create and supply an app password manually, the OAuth2 becomes more logical (and easier for the users themselves).

**Comment by snuglinux** [comment]
To write my program I will use application passwords. But still I decided to check OAuth2. 
I did not immediately notice that the client.dat file appeared :). 
I filled it out and got the following:
![image](https://user-images.githubusercontent.com/23461484/211921336-2d26a1af-48f3-42bf-8528-67810e246c64.png)

**Comment by rvk01** [comment]
> To write my program I will use application passwords. But still I decided to check OAuth2. I did not immediately notice that the client.dat file appeared :). I filled it out and got the following: x

Yes, the client.dat is created with the invalid credentials so that you can change them afterwards.
The message in the browser states that the program should have access.
But I see that you get a message "no scope specified in GetAccess".
That should only happen if you deselected Mail access (which I can't see because it is behind the browser).

Click "Remove tokens.dat" to let the authentication happen again.
Check the "Access to Mail" checkbox and click "Get Access".
After that it should work.

**Comment by snuglinux** [comment]
My tokens.dat file is not being created. I will not torture you, I will use application passwords. Thank you for your help!

**Comment by rvk01** [comment]
> My tokens.dat file is not being created. I will not torture you, I will use application passwords. Thank you for your help!

tokens.dat is only saved after successful retrieval of the account information. Maybe the scopes for your client_id are not set properly (which need to be set in the "OAuth consent screen" of the newly created project). At least ./auth/userinfo.email and ./auth/userinfo.profile need to be set. After that scope https://mail.google.com/ needs to be set for SMTP access. The other scopes don't need to be set (I think) but the authentication screen will give an extra warning if more scope is asked then registered with Google. And for my commercial program I had to go through the review process of the consent screen to allow my app to have access to other users mail (but for testing you could assign a test-user). 

In the screen below there are a few too many scopes set but it does work with this client_id. (I think https://mail.google.com/ will give full access already.)

![n45Usu3](https://user-images.githubusercontent.com/10880106/211930052-09874faf-9254-43b9-9635-adba37fbc638.png)

Yeah, app passwords are much easier 🤣

**Comment by snuglinux** [comment]
checked:
![image](https://user-images.githubusercontent.com/23461484/211932386-779343d4-488f-4fdf-8462-1a0c27a6c59c.png)
It still doesn't work :)
> Yeah, app passwords are much easier rofl 
- that's for sure :)

**Comment by rvk01** [comment]
> checked: yy It still doesn't work :)
> 

I'll update the project tomorrow with some last minute changes and a new test-project client_id to see if that one does work. I'll try to note down how I created the new test-project with all it's settings.

**Comment by rvk01** [comment]
> It still doesn't work :)
I'm not sure what error you are now still getting.

I've updated the project. I removed the old test_oauth2 and replaced it with a test_full (which isn't fully ready yet) and a slimmed down test_gmail project for just testing smtp (without all the Google Drive stuff). That last one should work now.

I can't create a client_id for everyone to use because without publishing (and hoging through the review process), only a specified test-user(s) can use the client_id. (In the far past this was not needed but Google required this since about mid 2021)
I described every step I did for creating a new project in the README.md.
You can download the .json and copy it to client.json in the app directory.

Hopefully it works now :) (Otherwise I need to know the error and scope settings)

**Comment by snuglinux** [comment]
I checked test_gmail.lpi and it finally worked. It looks like there was a problem in some of the libeay32.dll, libssl32.dll or ssleay32.dll libraries, I re-wrote them into the project and GetAccess was successful. Thank you very much for your help! It would be nice to add an IMAP example :)

**Comment by rvk01** [comment]
>  It would be nice to add an IMAP example :)
In my commercial application I use the authentication to push a draft mail via .eml format to the draft folder of Gmail (via Google API). After that I open up a browser so the user can finish the draft and send it manually (just like opening a new mail with Outlook etc). I do that because the downside of SMTP is that it is sent directly. I think I also have some code to read the inbox (to see if certain mail has arrived) but never implemented it. If I get some time the next days I can see if I can complete the seperate tab to include a inbox viewer (via IMAP). IMAP is one standard (which should be easy to implement). There is also another option of using json (Google API) to read and write messages. That's not standard IMAP.

**Comment by rvk01** [comment]
> It would be nice to add an IMAP example :)

I added a method to use IMAP. In the test_gmail you can click "Get Inbox" to retrieve the INBOX messages.
I assume you can use the standard TIMAPSend?
My new TmyIMAPSend (changed TIMAPSend) does the DoXOAuth2 (AUTHENTICATE XOAUTH2) so the IMAP can be used.

The test app only retrieves the INBOX but if you know how to use TIMAPSend you can expand it so it does everything with IMAP you want. If you need help with IMAP command, then let me know.

**Comment by snuglinux** [comment]
Checked, the example with imap works! One of these days I will figure it out and try to integrate it into my program. Many thanks to the author for your help!
